/**
 * Base IaC Exporter
 *
 * Interface and base functionality for IaC exporters.
 */

import type { FileDiff } from '../types.js';

/**
 * Supported IaC formats
 */
export type IaCFormat = 'terraform' | 'opentofu' | 'pulumi' | 'ansible' | 'cloudformation';

/**
 * Export options
 */
export interface ExportOptions {
  /** Output format */
  format: IaCFormat;
  /** Target provider (aws, gcp, azure, etc.) */
  provider?: string;
  /** Resource naming prefix */
  prefix?: string;
  /** Additional tags to apply */
  tags?: Record<string, string>;
  /** Include comments explaining changes */
  includeComments?: boolean;
  /** Generate variables file */
  generateVariables?: boolean;
  /** Output directory */
  outputDir?: string;
}

/**
 * Export result
 */
export interface ExportResult {
  /** Generated IaC files */
  files: ExportedFile[];
  /** Summary of exported resources */
  summary: ExportSummary;
  /** Warnings during export */
  warnings: string[];
}

/**
 * Exported file
 */
export interface ExportedFile {
  /** File path */
  path: string;
  /** File content */
  content: string;
  /** File type */
  type: 'main' | 'variables' | 'outputs' | 'provider' | 'module' | 'data';
}

/**
 * Export summary
 */
export interface ExportSummary {
  /** Number of resources */
  resourceCount: number;
  /** Resources by type */
  resourcesByType: Record<string, number>;
  /** Estimated changes */
  changes: {
    add: number;
    change: number;
    destroy: number;
  };
}

/**
 * Resource mapping from file changes
 */
export interface ResourceMapping {
  /** Resource type (e.g., 'local_file', 'null_resource') */
  type: string;
  /** Resource name */
  name: string;
  /** Resource attributes */
  attributes: Record<string, unknown>;
  /** Dependencies */
  dependsOn?: string[];
  /** Source file diff */
  sourceDiff: FileDiff;
}

/**
 * Base IaC Exporter interface
 */
export abstract class IaCExporter {
  /** Export format */
  abstract readonly format: IaCFormat;

  /** Format display name */
  abstract readonly displayName: string;

  /**
   * Export diffs to IaC
   */
  abstract export(diffs: FileDiff[], options?: Partial<ExportOptions>): Promise<ExportResult>;

  /**
   * Validate export result
   */
  abstract validate(result: ExportResult): Promise<ValidationResult>;

  /**
   * Convert file diff to resource mapping
   */
  protected diffToResource(diff: FileDiff, options: ExportOptions): ResourceMapping | null {
    const prefix = options.prefix ?? 'sandbox';
    const safeName = this.sanitizeName(diff.path);

    switch (diff.type) {
      case 'added':
        return {
          type: 'local_file',
          name: `${prefix}_${safeName}`,
          attributes: {
            filename: diff.path,
            content: diff.newContent ?? '',
            file_permission: diff.mode ?? '0644',
          },
          sourceDiff: diff,
        };

      case 'modified':
        return {
          type: 'local_file',
          name: `${prefix}_${safeName}`,
          attributes: {
            filename: diff.path,
            content: diff.newContent ?? '',
            file_permission: diff.mode ?? '0644',
          },
          sourceDiff: diff,
        };

      case 'deleted':
        // Deletions are handled differently - we return null and track separately
        return null;

      case 'renamed':
        return {
          type: 'local_file',
          name: `${prefix}_${safeName}`,
          attributes: {
            filename: diff.path,
            content: diff.newContent ?? '',
            file_permission: diff.mode ?? '0644',
          },
          sourceDiff: diff,
        };

      default:
        return null;
    }
  }

  /**
   * Sanitize a file path to be a valid resource name
   */
  protected sanitizeName(path: string): string {
    return path
      .replace(/^\//, '')
      .replace(/\//g, '_')
      .replace(/\./g, '_')
      .replace(/[^a-zA-Z0-9_]/g, '')
      .toLowerCase();
  }

  /**
   * Generate header comment
   */
  protected generateHeader(options: ExportOptions): string {
    const lines = [
      `# Generated by GWI Sandbox Export`,
      `# Format: ${this.displayName}`,
      `# Generated at: ${new Date().toISOString()}`,
      ``,
    ];

    if (options.includeComments) {
      lines.push(
        `# This file was auto-generated from sandbox execution diffs.`,
        `# Review carefully before applying to production.`,
        ``
      );
    }

    return lines.join('\n');
  }

  /**
   * Detect resource type from file path/content
   */
  protected detectResourceType(diff: FileDiff): DetectedResource {
    const path = diff.path.toLowerCase();

    // Configuration files
    if (path.endsWith('.conf') || path.endsWith('.cfg')) {
      return { category: 'config', suggestedType: 'template_file' };
    }

    // Nginx configuration
    if (path.includes('nginx') || path.includes('sites-available')) {
      return { category: 'webserver', suggestedType: 'template_file', hints: ['nginx'] };
    }

    // Systemd services
    if (path.endsWith('.service') || path.includes('systemd')) {
      return { category: 'systemd', suggestedType: 'template_file', hints: ['systemd'] };
    }

    // Docker files
    if (path.includes('docker') || path === 'dockerfile') {
      return { category: 'container', suggestedType: 'local_file', hints: ['docker'] };
    }

    // SSL/TLS certificates
    if (path.endsWith('.pem') || path.endsWith('.crt') || path.endsWith('.key')) {
      return { category: 'tls', suggestedType: 'local_sensitive_file', hints: ['tls', 'sensitive'] };
    }

    // Environment files
    if (path.includes('.env') || path.endsWith('environment')) {
      return { category: 'env', suggestedType: 'local_sensitive_file', hints: ['sensitive'] };
    }

    // Scripts
    if (path.endsWith('.sh') || path.endsWith('.bash')) {
      return { category: 'script', suggestedType: 'local_file', hints: ['executable'] };
    }

    // Default
    return { category: 'file', suggestedType: 'local_file' };
  }
}

/**
 * Validation result
 */
export interface ValidationResult {
  valid: boolean;
  errors: ValidationError[];
  warnings: ValidationWarning[];
}

/**
 * Validation error
 */
export interface ValidationError {
  file: string;
  line?: number;
  message: string;
  severity: 'error';
}

/**
 * Validation warning
 */
export interface ValidationWarning {
  file: string;
  line?: number;
  message: string;
  severity: 'warning';
}

/**
 * Detected resource information
 */
interface DetectedResource {
  category: string;
  suggestedType: string;
  hints?: string[];
}
