/**
 * Intent Receipt Formatting - Phase 18
 *
 * Standardizes Intent Receipt formatting for PR comments and audit logs.
 * Follows the "5W" pattern: Who, What, When, Why, Where
 *
 * @module @gwi/core/agents/intent-receipt
 */

import type { ExecutionResult } from './types.js';

/**
 * Standard Intent Receipt fields for PR comments
 */
export interface FormattedIntentReceipt {
  /** Markdown formatted comment */
  markdown: string;
  /** Plain text version */
  plainText: string;
  /** JSON structured data */
  json: Record<string, unknown>;
}

/**
 * Intent Receipt from execution result
 */
export type IntentReceiptData = ExecutionResult['intentReceipt'];

/**
 * Format an Intent Receipt as a PR comment
 *
 * Creates a standardized markdown comment that can be posted to GitHub PRs.
 * Includes the "5W" information plus policy/approval status.
 */
export function formatIntentReceiptAsComment(
  receipt: IntentReceiptData,
  options?: {
    /** Include full evidence details */
    includeEvidence?: boolean;
    /** Include trace/run IDs for debugging */
    includeTraceIds?: boolean;
    /** Custom footer text */
    footer?: string;
  }
): FormattedIntentReceipt {
  const { includeEvidence = true, includeTraceIds = false, footer } = options ?? {};

  // Build markdown sections
  const sections: string[] = [];

  // Header
  sections.push('## 🤖 GWI Intent Receipt');
  sections.push('');

  // Intent Summary
  sections.push('### Intent');
  sections.push(`> ${receipt.intent}`);
  sections.push('');

  // Change Summary
  sections.push('### Changes');
  sections.push(receipt.changeSummary);
  sections.push('');

  // 5W Table
  sections.push('### Details');
  sections.push('');
  sections.push('| Field | Value |');
  sections.push('|-------|-------|');
  sections.push(`| **Actor** | ${receipt.actor} |`);
  sections.push(`| **When** | ${formatTimestamp(receipt.when)} |`);
  sections.push(`| **Scope** | ${receipt.scope} |`);
  sections.push(`| **Policy** | ${receipt.policyApproval} |`);
  sections.push('');

  // Evidence (optional)
  if (includeEvidence && receipt.evidence) {
    sections.push('### Evidence');
    sections.push('');
    sections.push('```');
    sections.push(receipt.evidence);
    sections.push('```');
    sections.push('');
  }

  // Trace IDs (optional, for debugging)
  if (includeTraceIds && (receipt.traceId || receipt.runId)) {
    sections.push('<details>');
    sections.push('<summary>Debug Information</summary>');
    sections.push('');
    if (receipt.runId) {
      sections.push(`- **Run ID**: \`${receipt.runId}\``);
    }
    if (receipt.traceId) {
      sections.push(`- **Trace ID**: \`${receipt.traceId}\``);
    }
    sections.push('');
    sections.push('</details>');
    sections.push('');
  }

  // Footer
  sections.push('---');
  if (footer) {
    sections.push(footer);
  } else {
    sections.push('*Generated by [Git With Intent](https://github.com/git-with-intent)*');
  }

  const markdown = sections.join('\n');

  // Plain text version
  const plainText = [
    'GWI Intent Receipt',
    '==================',
    '',
    `Intent: ${receipt.intent}`,
    '',
    `Changes: ${receipt.changeSummary}`,
    '',
    `Actor: ${receipt.actor}`,
    `When: ${receipt.when}`,
    `Scope: ${receipt.scope}`,
    `Policy: ${receipt.policyApproval}`,
    '',
    `Evidence: ${receipt.evidence}`,
  ].join('\n');

  // JSON version
  const json: Record<string, unknown> = {
    intent: receipt.intent,
    changeSummary: receipt.changeSummary,
    actor: receipt.actor,
    when: receipt.when,
    scope: receipt.scope,
    policyApproval: receipt.policyApproval,
    evidence: receipt.evidence,
  };

  if (receipt.traceId) {
    json.traceId = receipt.traceId;
  }
  if (receipt.runId) {
    json.runId = receipt.runId;
  }

  return {
    markdown,
    plainText,
    json,
  };
}

/**
 * Format timestamp in a human-readable way
 */
function formatTimestamp(timestamp: string): string {
  try {
    const date = new Date(timestamp);
    return date.toLocaleString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      timeZoneName: 'short',
    });
  } catch {
    return timestamp;
  }
}

/**
 * Create a minimal Intent Receipt comment for quick operations
 */
export function formatMinimalIntentReceipt(
  receipt: IntentReceiptData
): string {
  return [
    '🤖 **GWI**',
    '',
    `> ${receipt.intent}`,
    '',
    `${receipt.changeSummary}`,
    '',
    `_by ${receipt.actor} at ${formatTimestamp(receipt.when)}_`,
  ].join('\n');
}

/**
 * Create an Intent Receipt for a plan review (before execution)
 */
export function formatPlanReviewComment(
  planSummary: string,
  requiredScopes: string[],
  riskLevel: string,
  confidence: number,
  affectedFiles: string[]
): string {
  const sections: string[] = [];

  sections.push('## 📋 GWI Implementation Plan');
  sections.push('');

  sections.push('### Summary');
  sections.push(`> ${planSummary}`);
  sections.push('');

  sections.push('### Risk Assessment');
  sections.push(`- **Risk Level**: ${riskLevel}`);
  sections.push(`- **Confidence**: ${confidence}%`);
  sections.push('');

  if (requiredScopes.length > 0) {
    sections.push('### Required Approvals');
    sections.push('');
    for (const scope of requiredScopes) {
      sections.push(`- [ ] \`${scope}\``);
    }
    sections.push('');
  }

  if (affectedFiles.length > 0) {
    sections.push('### Affected Files');
    sections.push('');
    const displayFiles = affectedFiles.slice(0, 10);
    for (const file of displayFiles) {
      sections.push(`- \`${file}\``);
    }
    if (affectedFiles.length > 10) {
      sections.push(`- _...and ${affectedFiles.length - 10} more_`);
    }
    sections.push('');
  }

  sections.push('---');
  sections.push('Reply with `/gwi approve` to proceed with execution.');

  return sections.join('\n');
}

/**
 * Create a success comment after PR creation
 */
export function formatSuccessComment(
  prUrl: string,
  receipt: IntentReceiptData
): string {
  return [
    '## ✅ GWI Execution Complete',
    '',
    `> ${receipt.intent}`,
    '',
    `**Pull Request Created**: ${prUrl}`,
    '',
    `${receipt.changeSummary}`,
    '',
    '---',
    `_Executed by ${receipt.actor} at ${formatTimestamp(receipt.when)}_`,
  ].join('\n');
}

/**
 * Create a failure comment
 */
export function formatFailureComment(
  error: string,
  receipt: IntentReceiptData
): string {
  return [
    '## ❌ GWI Execution Failed',
    '',
    `> ${receipt.intent}`,
    '',
    '### Error',
    '```',
    error,
    '```',
    '',
    '---',
    `_Attempted by ${receipt.actor} at ${formatTimestamp(receipt.when)}_`,
  ].join('\n');
}
