/**
 * Workspace Paths for Git With Intent
 *
 * Provides utilities for managing the sandboxed workspace where
 * CoderAgent writes generated code artifacts.
 *
 * The workspace is:
 * - Git-ignored (ephemeral)
 * - Safe for automated writes
 * - Isolated per-run to avoid conflicts
 *
 * @module @gwi/core/workspace
 */

import { resolve, join } from 'path';

// =============================================================================
// Types
// =============================================================================

/**
 * Workspace path configuration
 */
export interface WorkspacePaths {
  /** Root workspace directory (absolute path) */
  root: string;
  /** Directory for per-run subdirectories */
  runsDir: string;
}

/**
 * Files generated by CoderAgent for a run
 */
export interface RunArtifacts {
  /** Path to the plan file (plan.md) */
  planPath: string;
  /** Paths to patch files (patch-*.txt) */
  patchPaths: string[];
  /** Optional notes or logs */
  notes?: string;
}

// =============================================================================
// Path Utilities
// =============================================================================

/**
 * Get workspace paths configuration.
 *
 * Uses GWI_WORKSPACE_ROOT environment variable if set,
 * otherwise defaults to 'workspace' at repo root.
 *
 * @returns Workspace paths with absolute paths
 */
export function getWorkspacePaths(): WorkspacePaths {
  const workspaceRoot = process.env.GWI_WORKSPACE_ROOT || 'workspace';

  // Resolve to absolute path relative to current working directory
  const root = resolve(process.cwd(), workspaceRoot);

  return {
    root,
    runsDir: join(root, 'runs'),
  };
}

/**
 * Get the workspace directory for a specific run.
 *
 * @param runId - Unique run identifier
 * @returns Absolute path to the run's workspace directory
 */
export function getRunWorkspaceDir(runId: string): string {
  const { runsDir } = getWorkspacePaths();
  // Sanitize runId to prevent path traversal
  const sanitizedRunId = runId.replace(/[^a-zA-Z0-9_-]/g, '_');
  return join(runsDir, sanitizedRunId);
}

/**
 * Get the expected artifact paths for a run.
 *
 * @param runId - Unique run identifier
 * @returns Paths where artifacts will be written
 */
export function getRunArtifactPaths(runId: string): { planPath: string; patchDir: string } {
  const runDir = getRunWorkspaceDir(runId);
  return {
    planPath: join(runDir, 'plan.md'),
    patchDir: runDir,
  };
}

/**
 * Generate a patch file path for a specific file.
 *
 * @param runId - Unique run identifier
 * @param index - Patch index (1-based)
 * @returns Path to the patch file
 */
export function getPatchFilePath(runId: string, index: number): string {
  const runDir = getRunWorkspaceDir(runId);
  const paddedIndex = String(index).padStart(3, '0');
  return join(runDir, `patch-${paddedIndex}.txt`);
}
